language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
script:
  - npm install
  - ng build --base-href /health-ledger-frontend/
  - cp dist/health-ledger-frontend/index.html dist/health-ledger-frontend/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/health-ledger-frontend
  on:
    branch: master
